server:
  port: 8081

application:
  name: card-service
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTERY_URL}

spring:
  datasource:
    url: jdbc:h2:mem:cardsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

test:
  value: hello

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0