spring:
  application:
    name: cards-service
server:
    port: 8083
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
      show-details=always
