server:
  port: 8081
spring:
  application:
    name: card-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

test:
  value: hello

management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose all actuator endpoints
  endpoint:
    health:
      show-details: always   # show full health details
