spring:
  application:
    name: card-service
server:
    port: 8083
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_REGISTERY_URL}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

