spring:
  application:
    name: dg-ms-customer
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_REGISTERY_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
      show-details=always


digital:
  url:
    cards: dg-ms-card


