spring:
  application:
    name: dg-ms-customer
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_REGISTERY_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
      show-details=always


digital:
  url:
    cards: dg-ms-card

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: none
  resource-attributes:
    service.name: ${OTEL_SERVICE_NAME}
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}




