spring:
  application:
    name: dg-ms-customer
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_REGISTERY_URL}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317
  observations:
    key-values:
      service.name: ${spring.application.name}
      environment: dev






