spring:
  application:
    name: dg-ms-customer
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_REGISTERY_URL}


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"



